version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: bitly_postgres
    restart: always
    environment:
      POSTGRES_USER: bitly_user
      POSTGRES_PASSWORD: bitly_password
      POSTGRES_DB: bitly_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bitly_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bitly_user -d bitly_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  write_service:
    build:
      context: ../../
      dockerfile: deployment/docker_compose/Dockerfile
    container_name: bitly_write_service
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://bitly_user:bitly_password@postgres:5432/bitly_db
      PYTHONPATH: /app
    volumes:
      - ../../backend:/app
    ports:
      - "8000:8000"
    networks:
      - bitly_network
    command: >
      sh -c "
        cd /app &&
        sleep 5 &&
        alembic upgrade head &&
        uvicorn bitly.server.write_service.api:app --host 0.0.0.0 --port 8000 --reload"

  read_service:
    build:
      context: ../../
      dockerfile: deployment/docker_compose/Dockerfile
    container_name: bitly_read_service
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://bitly_user:bitly_password@postgres:5432/bitly_db
      PYTHONPATH: /app
    volumes:
      - ../../backend:/app
    ports:
      - "8001:8001"
    networks:
      - bitly_network
    command: >
      sh -c "
        cd /app &&
        sleep 5 &&
        uvicorn bitly.server.read_service.api:app --host 0.0.0.0 --port 8001 --reload"

volumes:
  postgres_data:

networks:
  bitly_network:
